#pragma once

#include "ARIRANG/Arirang_sha3.h"
#include "Abacus/Abacus_sha3.h"
#include "Aurora/Aurora_sha3.h"
#include "BMW/BMW_sha3.h"
#include "Blake/Blake_sha3.h"
#include "Blender/Blender_sha3.h"
#include "Boole/Boole_sha3.h"
#include "CHI/Chi_sha3.h"
#include "CRUNCH/Crunch_sha3.h"
#include "Cheetah/Cheetah_sha3.h"
#include "CubeHash/CubeHash_sha3.h"
#include "DCH/DCH_sha3.h"
#include "DynamicSHA/DSHA_sha3.h"
#include "DynamicSHA2/DSHA2_sha3.h"
#include "ECHO/Echo_sha3.h"
// #include "ECOH/Ecoh_sha3.h"
#include "EDON/Edon_sha3.h"
// #include "EnRUPT/Enrupt_sha3.h"
#include "ESSENCE/Essence_sha3.h"
#include "Fugue/Fugue_sha3.h"
#include "Grostl/Grostl_sha3.h"
#include "Hamsi/Hamsi_sha3.h"
#include "JH/JH_sha3.h"
#include "Keccak/Keccak_sha3.h"
#include "Khichidi/Khichidi_sha3.h"
#include "Lane/Lane_sha3.h"
#include "Lesamnta/Lesamnta_sha3.h"
#include "Luffa/Luffa_sha3.h"
// #include "LUX/Lux_sha3.h"
#include "MCSSHA3/Mcssha_sha3.h"
#include "MD6/MD6_sha3.h"
#include "MeshHash/MeshHash_sha3.h"
#include "NaSHA/Nasha_sha3.h"
// #include "SANDstorm/Sandstorm_sha3.h"
#include "SHAvite3/SHAvite_sha3.h"
#include "SIMD/Simd_sha3.h"
#include "Sarmal/Sarmal_sha3.h"
#include "Shabal/Shabal_sha3.h"
#include "Shamata/Shamata_sha3.h"
#include "Skein/Skein_sha3.h"
#include "SpectralHash/SpectralHash_sha3.h"
#include "StreamHash/StreamHash_sha3.h"
// #include "SWIFFTX/Swifftx_sha3.h"
#include "Tangle/Tangle_sha3.h"
// #include "TIB3/Tib_sha3.h"
#include "Tangle2/Tangle2_sha3.h"
#include "Twister/Twister_sha3.h"
//#include "Vortex/Vortex_sha3.h"
#include "WaMM/Wamm_sha3.h"
#include "Waterfall/Waterfall_sha3.h"
