#include "sha1/sha1_factory.h"
#include "sha2/sha256_factory.h"
#include "md5/md5_factory.h"
#include "gost/gost_factory.h"
#include "ripemd160/ripemd160_factory.h"
#include "tiger/tiger_factory.h"
#include "whirlpool/whirlpool_factory.h"
